[2025-03-31T21:59:26.264+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-31T21:59:26.272+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data_pipeline.query_avg_temp manual__2025-03-31T21:59:15.682061+00:00 [queued]>
[2025-03-31T21:59:26.275+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data_pipeline.query_avg_temp manual__2025-03-31T21:59:15.682061+00:00 [queued]>
[2025-03-31T21:59:26.275+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-31T21:59:26.281+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): query_avg_temp> on 2025-03-31 21:59:15.682061+00:00
[2025-03-31T21:59:26.283+0000] {standard_task_runner.py:64} INFO - Started process 220 to run task
[2025-03-31T21:59:26.284+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sensor_data_pipeline', 'query_avg_temp', 'manual__2025-03-31T21:59:15.682061+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpw9fo6ugr']
[2025-03-31T21:59:26.285+0000] {standard_task_runner.py:91} INFO - Job 48: Subtask query_avg_temp
[2025-03-31T21:59:26.298+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data_pipeline.query_avg_temp manual__2025-03-31T21:59:15.682061+00:00 [running]> on host airflow
[2025-03-31T21:59:26.326+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sensor_data_pipeline' AIRFLOW_CTX_TASK_ID='query_avg_temp' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T21:59:15.682061+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T21:59:15.682061+00:00'
[2025-03-31T21:59:26.326+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-31T21:59:26.331+0000] {pipeline.py:178} INFO - Executing query to get average temperature by location and day
[2025-03-31T21:59:26.334+0000] {base.py:84} INFO - Using connection ID 'hive_default' for task execution.
[2025-03-31T21:59:26.352+0000] {hive.py:475} INFO - USE `default`
[2025-03-31T21:59:26.361+0000] {hive.py:475} INFO - 
            SELECT
                record_datetime,
                location,
                AVG(temperature_salon) AS avg_temperature_salon,
                AVG(temperature_chambre) AS avg_temperature_chambre,
                AVG(temperature_bureau) AS avg_temperature_bureau,
                AVG(temperature_exterieur) AS avg_temperature_exterieur
            FROM sensors.records
            GROUP BY record_datetime
        
[2025-03-31T21:59:26.440+0000] {pipeline.py:208} ERROR - ‚ùå Error creating table: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10025, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10025]: Line 4:16 Expression not in GROUP BY key 'location'"), operationHandle=None)
Traceback (most recent call last):
  File "/opt/airflow/dags/pipeline.py", line 194, in get_avg_temperature_by_location_and_day
    rows = cursor.execute(query)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10025, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10025]: Line 4:16 Expression not in GROUP BY key 'location'"), operationHandle=None)
[2025-03-31T21:59:26.441+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-31T21:59:26.441+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 194, in get_avg_temperature_by_location_and_day
    rows = cursor.execute(query)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 481, in execute
    _check_status(response)
  File "/home/airflow/.local/lib/python3.9/site-packages/pyhive/hive.py", line 611, in _check_status
    raise OperationalError(response)
pyhive.exc.OperationalError: TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10025, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10025]: Line 4:16 Expression not in GROUP BY key 'location'"), operationHandle=None)
[2025-03-31T21:59:26.443+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sensor_data_pipeline, task_id=query_avg_temp, run_id=manual__2025-03-31T21:59:15.682061+00:00, execution_date=20250331T215915, start_date=20250331T215926, end_date=20250331T215926
[2025-03-31T21:59:26.449+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 48 for task query_avg_temp (TExecuteStatementResp(status=TStatus(statusCode=3, infoMessages=['Server-side error; please check HS2 logs.'], sqlState='42000', errorCode=10025, errorMessage="Error while compiling statement: FAILED: SemanticException [Error 10025]: Line 4:16 Expression not in GROUP BY key 'location'"), operationHandle=None); 220)
[2025-03-31T21:59:26.467+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-31T21:59:26.474+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T21:59:26.474+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
