[2025-03-31T21:37:12.806+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-31T21:37:12.817+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data_pipelinew.publish_csv manual__2025-03-30T16:45:43.154862+00:00 [queued]>
[2025-03-31T21:37:12.820+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data_pipelinew.publish_csv manual__2025-03-30T16:45:43.154862+00:00 [queued]>
[2025-03-31T21:37:12.820+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-31T21:37:12.827+0000] {taskinstance.py:2330} INFO - Executing <Task(ProduceToTopicOperator): publish_csv> on 2025-03-30 16:45:43.154862+00:00
[2025-03-31T21:37:12.830+0000] {standard_task_runner.py:64} INFO - Started process 180 to run task
[2025-03-31T21:37:12.832+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sensor_data_pipelinew', 'publish_csv', 'manual__2025-03-30T16:45:43.154862+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpu5fje1gu']
[2025-03-31T21:37:12.833+0000] {standard_task_runner.py:91} INFO - Job 19: Subtask publish_csv
[2025-03-31T21:37:12.847+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data_pipelinew.publish_csv manual__2025-03-30T16:45:43.154862+00:00 [running]> on host airflow
[2025-03-31T21:37:12.880+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sensor_data_pipelinew' AIRFLOW_CTX_TASK_ID='publish_csv' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T16:45:43.154862+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T16:45:43.154862+00:00'
[2025-03-31T21:37:12.881+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-31T21:37:12.890+0000] {base.py:84} INFO - Using connection ID 'kafka_default' for task execution.
[2025-03-31T21:37:12.892+0000] {produce.py:41} INFO - Producer <cimpl.Producer object at 0xffff8ddd4540>
[2025-03-31T21:37:12.892+0000] {pipeline.py:39} INFO - Starting to read CSV file from /opt/airflow/datasets/home_temperature_and_humidity_smoothed_filled.csv
[2025-03-31T21:37:12.901+0000] {pipeline.py:42} INFO - Successfully read CSV with 8137 rows
[2025-03-31T21:37:12.901+0000] {pipeline.py:44} INFO - Renaming 'timestamp' column to 'record_datetime'
[2025-03-31T21:37:12.901+0000] {pipeline.py:47} INFO - Converting DataFrame to dictionary records
[2025-03-31T21:37:12.914+0000] {pipeline.py:50} INFO - Converting records to JSON strings
[2025-03-31T21:37:12.955+0000] {pipeline.py:53} INFO - ðŸ“¤ Prepared 8137 messages to send to Kafka topic 'sensores'
[2025-03-31T21:37:12.956+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-31T21:37:12.957+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 126, in execute
    for k, v in producer_callable():
ValueError: too many values to unpack (expected 2)
[2025-03-31T21:37:12.959+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sensor_data_pipelinew, task_id=publish_csv, run_id=manual__2025-03-30T16:45:43.154862+00:00, execution_date=20250330T164543, start_date=20250331T213712, end_date=20250331T213712
[2025-03-31T21:37:12.964+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 19 for task publish_csv (too many values to unpack (expected 2); 180)
[2025-03-31T21:37:12.971+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-31T21:37:12.981+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T21:37:12.982+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
