[2025-03-30T16:46:23.342+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-30T16:46:23.352+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data_pipelinew.send_to_kafka manual__2025-03-30T16:41:13.701220+00:00 [queued]>
[2025-03-30T16:46:23.354+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data_pipelinew.send_to_kafka manual__2025-03-30T16:41:13.701220+00:00 [queued]>
[2025-03-30T16:46:23.354+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-03-30T16:46:23.361+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): send_to_kafka> on 2025-03-30 16:41:13.701220+00:00
[2025-03-30T16:46:23.363+0000] {standard_task_runner.py:64} INFO - Started process 191 to run task
[2025-03-30T16:46:23.366+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sensor_data_pipelinew', 'send_to_kafka', 'manual__2025-03-30T16:41:13.701220+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp8p0uu83a']
[2025-03-30T16:46:23.367+0000] {standard_task_runner.py:91} INFO - Job 16: Subtask send_to_kafka
[2025-03-30T16:46:23.384+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data_pipelinew.send_to_kafka manual__2025-03-30T16:41:13.701220+00:00 [running]> on host airflow
[2025-03-30T16:46:23.504+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sensor_data_pipelinew' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T16:41:13.701220+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T16:41:13.701220+00:00'
[2025-03-30T16:46:23.505+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-30T16:46:23.514+0000] {base.py:84} INFO - Using connection ID 'kafka_default' for task execution.
[2025-03-30T16:46:23.514+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-30T16:46:23.514+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 73, in send_message_to_kafka
    producer = Producer(
cimpl.KafkaException: KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "bootstrap_servers""}
[2025-03-30T16:46:23.516+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=sensor_data_pipelinew, task_id=send_to_kafka, run_id=manual__2025-03-30T16:41:13.701220+00:00, execution_date=20250330T164113, start_date=20250330T164623, end_date=20250330T164623
[2025-03-30T16:46:23.522+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 16 for task send_to_kafka (KafkaError{code=_INVALID_ARG,val=-186,str="No such configuration property: "bootstrap_servers""}; 191)
[2025-03-30T16:46:23.550+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-30T16:46:23.556+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T16:46:23.557+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
