[2025-03-30T16:41:21.265+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-03-30T16:41:21.274+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sensor_data_pipelinew.send_to_kafka manual__2025-03-30T16:41:13.701220+00:00 [queued]>
[2025-03-30T16:41:21.276+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sensor_data_pipelinew.send_to_kafka manual__2025-03-30T16:41:13.701220+00:00 [queued]>
[2025-03-30T16:41:21.277+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-03-30T16:41:21.282+0000] {taskinstance.py:2330} INFO - Executing <Task(ProduceToTopicOperator): send_to_kafka> on 2025-03-30 16:41:13.701220+00:00
[2025-03-30T16:41:21.284+0000] {standard_task_runner.py:64} INFO - Started process 189 to run task
[2025-03-30T16:41:21.286+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'sensor_data_pipelinew', 'send_to_kafka', 'manual__2025-03-30T16:41:13.701220+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpiurxwikw']
[2025-03-30T16:41:21.287+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask send_to_kafka
[2025-03-30T16:41:21.300+0000] {task_command.py:426} INFO - Running <TaskInstance: sensor_data_pipelinew.send_to_kafka manual__2025-03-30T16:41:13.701220+00:00 [running]> on host airflow
[2025-03-30T16:41:21.324+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='sensor_data_pipelinew' AIRFLOW_CTX_TASK_ID='send_to_kafka' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T16:41:13.701220+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T16:41:13.701220+00:00'
[2025-03-30T16:41:21.325+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-03-30T16:41:21.332+0000] {base.py:84} INFO - Using connection ID 'kafka_default' for task execution.
[2025-03-30T16:41:21.333+0000] {produce.py:41} INFO - Producer <cimpl.Producer object at 0xffff8ceb3ae0>
[2025-03-30T16:41:21.333+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-03-30T16:41:21.334+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/kafka/operators/produce.py", line 117, in execute
    self.producer_function = import_string(self.producer_function)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 39, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named '{{ ti'
[2025-03-30T16:41:21.336+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=sensor_data_pipelinew, task_id=send_to_kafka, run_id=manual__2025-03-30T16:41:13.701220+00:00, execution_date=20250330T164113, start_date=20250330T164121, end_date=20250330T164121
[2025-03-30T16:41:21.340+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task send_to_kafka (No module named '{{ ti'; 189)
[2025-03-30T16:41:21.349+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-03-30T16:41:21.357+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T16:41:21.357+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
